version: '3'
services:
  user:
    build: './user-service'
    ports:
      - "3001:3001"
    volumes:
      - ./user-service:/app
  product:
    build: './product-service'
    ports:
      - "3002:3002"
    volumes:
      - ./product-service:/app
  order:
    build: './order-service'
    ports:
      - "3003:3003"
    volumes:
      - ./order-service:/app
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf